### ISSUE TITLE
Small update

### ISSUE THREAD

**Issue by julien9999** [mpociot/TiCircularSlider#1]
Hi, this module is great, good job.
Could you add the possibility to change the slider value? or maybe it is already available? if yes how?
like if I press a button, slider.value = 50.
many thanks

**Comment by hansemannn** [comment]
Part of this PR: https://github.com/mpociot/TiCircularSlider/pull/16

**Comment by kgividen** [comment]
This is great and what I asked Hans to do is working for iOS but still needs to be done for Android...
